services:
  actual_server:
    image: docker.io/actualbudget/actual-server@sha256:e82b7302b0db7f8fa063159e8bddc07443bb83761798dc9ba84fe1b3df62d74f
    # ports:
    # This line makes Actual available at port 5006 of the device you run the server on,
    # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
    # - '5006:5006'
    # environment:
    # Updated paths to point to the mounted certificate files inside the container
    # - ACTUAL_HTTPS_CERT=/certs/ubuntu-server.taile7003c.ts.net.crt
    # - ACTUAL_HTTPS_KEY=/certs/ubuntu-server.taile7003c.ts.net.key
    # - ACTUAL_PORT=5006
    # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
    # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
    # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
    # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - actual_data:/data
    networks:
      - ingress
    expose:
      - "5006"
    healthcheck:
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2@sha256:2017b0e180cfe7f896117e2c10a05d6036c396de426112875456b808d8a51c6b
    restart: unless-stopped
    env_file: ./.backup.env
    volumes:
      - actual_data:/backup/actual-budget-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  ingress:
    external: true

volumes:
  actual_data:
