$ANSIBLE_VAULT;1.1;AES256
39363837656634346335306532346533343664356466356436313733613261613434306163316437
3737396166613934323066303939323139366432366536630a353937666564626265313962646562
39343339316436306264636664666630343634396562333235636235393636626137386535386334
3630666364373835620a653739386631383532653231376566346666396332386532663937653038
61653363326639653037373464643633633161396130323561396236396235633562323461353163
66343030343835303439643830366138626431623933663639663030316166333162353830653762
38336262303337643465363765396138363438663665393463623839623437373331636333373137
38303036363461636232366562306366663137316235353665363433636365646239636537393838
33316534393230653162353463326364386132346336623033666535626465656264643132643135
62363666303830383265643334633565636235613333636237373666303632643363366561323735
65626337333335366437336666363132376562373964333364303432306638626336346639386438
31653865333363313364646537666666333635346536656532366661383433386236306565656635
32333830323862383733363538323238666161623965653532323961333765326231636465383634
34636366613364623161393065336565333137373563323865643733393633656230613738646132
61623064386437666435623038373263613630656137336461616263613937376238383337316166
34396337643165646239666139623361323735386665333635353634316435343831383364616438
65313338643539323363666166326538316238346565346135383239376139653032616365666561
3839383635323330333937346634633136373466393030346539
