$ANSIBLE_VAULT;1.1;AES256
30663862353263386635623739643436376664373436316566373232366463303363313533333633
6461386634383562373462363964393239633461663866650a333265306536666136366661613839
35353430336536333862326162363763616336643830613762613930383462626265613363363362
6430313331653438610a623361643930373639636636623962363065633733643066306363373963
30396233313661306566393137663137666233656538336135623065343332336138633666326532
30393937346434636561633438333064663431636163366661366164356261646363326130346632
35373639353433383539333634393362653735663262316234343830373634386437313166643631
65323662613062333263616465646663646534323636353232366632663435373062663964386161
37313635303566396262306465373765623030643764306336626363346637383936613232666666
6538326230613437333037663738653066383532326266373961
