- name: Setup docker
  hosts: webservers
  become: true
  roles:
    - geerlingguy.docker

- name: Clone homeserver repo
  hosts: webservers
  become: true # You likely need sudo to write to /opt
  tasks:
    - name: Git clone the homeserver repository
      ansible.builtin.git:
        repo: "https://github.com/kennethlieyanto/homeserver.git"
        dest: /opt/homeserver
        version: main
        update: true
