services:
  nginx:
    image: "jc21/nginx-proxy-manager@sha256:cd9eba29ca132cb006729f2cb2660126453f84818c2f7d75963ad7b61ef696bd"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      TZ: "Asia/Jakarta"
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - ingress
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2@sha256:2017b0e180cfe7f896117e2c10a05d6036c396de426112875456b808d8a51c6b
    restart: unless-stopped
    env_file: ./.backup.env
    volumes:
      - npm_data:/backup/npm-data-backup:ro
      - npm_letsencrypt:/backup/npm-letsencrypt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  ingress:
    external: true
